# Makefile for uClibc (sh/libubacktrace)
#
# Copyright (C) 2010 STMicroelectronics Ltd
# Author: Carmelo Amoroso <carmelo.amoroso@st.com>

# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libubacktrace_ARCH_SRC-y := backtrace.c

# -fexections is required for backtrace to work using dwarf2
CFLAGS-backtrace.c := -fexceptions
