# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := ptrace.c brk.c

SSRC := __longjmp.S bsd-_setjmp.S bsd-setjmp.S clone.S setjmp.S vfork.S

ifneq ($(HAVE_ELF),y)
ARCH_HEADERS := float.h
else
ARCH_HEADERS := fpu_control.h
endif

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
