# uClibc pwd_grp tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

TESTS := test_pwd test_grp pwcat grcat getgroups

include ../Test.mak

DODIFF_test_pwd  := 1
DODIFF_test_grp  := 1
DODIFF_pwcat     := 1
DODIFF_grcat     := 1
DODIFF_getgroups := 1
