# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := brk.c sigaction.c __syscall_error.c

SSRC := \
	__longjmp.S vfork.S clone.S setjmp.S bsd-setjmp.S bsd-_setjmp.S \
	sync_file_range.S syscall.S mmap.S mmap64.S

ifeq ($(UCLIBC_HAS_ADVANCED_REALTIME),y)
SSRC += posix_fadvise64.S
CSRC += posix_fadvise.c
endif

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
