# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := brk.c __syscall_error.c qp_ops.c

ifneq ($(UCLIBC_HAS_THREADS_NATIVE),y)
CSRC += sigaction.c
endif

SSRC := \
	__longjmp.S setjmp.S bsd-setjmp.S bsd-_setjmp.S \
	syscall.S urem.S udiv.S umul.S sdiv.S rem.S pipe.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
