# uClibc unistd tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

include ../Test.mak

OPTS_getopt      := -abcXXX -9
OPTS_getopt_long := --add XXX --delete YYY --verbose
OPTS_tstgetopt   := -a -b -cfoobar --required foobar --optional=bazbug --none random --col --color --colour
