# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := mmap.c __syscall_error.c pread_write.c ioctl.c

SSRC := \
	__longjmp.S setjmp.S bsd-setjmp.S bsd-_setjmp.S brk.S \
	clone.S __uClibc_syscall.S syscall.S vfork.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
