# uClibc stdlib tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

include ../Test.mak

DODIFF_qsort       := 1
DODIFF_testatexit  := 1
DODIFF_teston_exit := 1
DODIFF_teststrtol  := 1
