# uClibc args tests
# Licensed under the GNU Library General Public License, see COPYING.LIB

include ../Test.mak

OPTS_arg_test = a b c d e f g h
WRAPPER_arg_test = \
	env -i \
	ENVVAR=123 \
	SOMETHING=sldajfasdf \
	BLAHBLAH=" hi hi "
