# Makefile for uClibc NPTL
#
# Copyright (C) 2005 Steven J. Hill <sjhill@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#
subdirs += libpthread/nptl/sysdeps/$(TARGET_ARCH)/$(TARGET_SUBARCH)/sparv9
libpthread_CSRC = sparc32/pthread_spin_lock.c \
				  sparc32/pthread_spin_trylock.c

CFLAGS-pthread_spin_lock.c += -D_GNU_SOURCE

CFLAGS-sparc = $(SSP_ALL_CFLAGS)

