# uClibc pthread tests
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.

TESTS_DISABLED += cancellation-points
top_builddir=../../
include ../Rules.mak
-include Makefile.in
include ../Test.mak
