# Makefile for uClibc
#
# Copyright (c) 2007  STMicroelectronics Ltd
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

libm_ARCH_SRC:=$(wildcard $(libm_ARCH_fpu_DIR)/*.c)
libm_ARCH_OBJ:=$(patsubst $(libm_ARCH_fpu_DIR)/%.c,$(libm_ARCH_fpu_OUT)/%.o,$(libm_ARCH_SRC))

libm_ARCH_OBJS:=$(libm_ARCH_OBJ)

ifeq ($(DOPIC),y)
libm-a-y+=$(libm_ARCH_OBJS:.o=.os)
else
libm-a-y+=$(libm_ARCH_OBJS)
endif
libm-so-y+=$(libm_ARCH_OBJS:.o=.os)
